# Generated by Django 4.2.6 on 2023-11-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='role',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='roles',
            field=models.ManyToManyField(related_name='apiuser', to='users.role'),
        ),
    ]
