# Generated by Django 4.2.6 on 2023-11-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_apiuser_role_apiuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='password',
        ),
    ]
