# Generated by Django 4.2.6 on 2023-10-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urbanizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanizationManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=48)),
                ('last_name', models.CharField(max_length=48)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('urbanization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urbanization_manager', to='urbanizations.urbanization')),
            ],
        ),
    ]
