# Generated by Django 4.2.6 on 2023-10-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizations', '0001_initial'),
        ('urbanization_managers', '0002_alter_urbanizationmanager_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanizationmanager',
            name='urbanization',
            field=models.ForeignKey(db_column='urbanization_id', on_delete=django.db.models.deletion.CASCADE, to='urbanizations.urbanization'),
        ),
    ]
