# Generated by Django 4.2.6 on 2023-10-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Urbanization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('street', models.CharField(max_length=48)),
                ('number', models.CharField(max_length=8)),
                ('neighborhood', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('zip_code', models.PositiveIntegerField()),
                ('houses', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=64)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urbanization', to='urbanizations.plan')),
            ],
        ),
    ]
