# Generated by Django 4.2.6 on 2023-10-30 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Urbanizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('street', models.CharField(max_length=48)),
                ('number', models.CharField(max_length=8)),
                ('neighborhood', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('zip_code', models.PositiveSmallIntegerField(max_length=5)),
                ('houses', models.PositiveIntegerField(max_length=9999)),
                ('is_active', models.BooleanField()),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=64)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urbanizations', to='urbanizations.plans')),
            ],
        ),
    ]
