# Generated by Django 4.2.6 on 2023-10-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizations', '0002_alter_plans_price_urbanizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbanizations',
            name='houses',
        ),
        migrations.RemoveField(
            model_name='urbanizations',
            name='zip_code',
        ),
    ]
