# Generated by Django 4.2.6 on 2023-10-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urbanizations', '0004_rename_plan_id_urbanizations_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urbanization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('street', models.CharField(max_length=48)),
                ('number', models.CharField(max_length=8)),
                ('neighborhood', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('is_active', models.BooleanField()),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.DeleteModel(
            name='Urbanizations',
        ),
        migrations.AddField(
            model_name='urbanization',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urbanization', to='urbanizations.plan'),
        ),
    ]
