# Generated by Django 4.2.6 on 2023-10-31 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urbanizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('street', models.CharField(max_length=48)),
                ('number', models.CharField(max_length=8)),
                ('neighborhood', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('zip_code', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('urbanization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='urbanizations.urbanization')),
            ],
        ),
    ]
